receivers:
  hostmetrics:
    collection_interval: 10s
    root_path: /hostfs
    scrapers:
      cpu: {}
      load: {}
      memory: {}
      disk: {}
      filesystem: {}
      network: {}
      paging: {}
      processes: {}

processors:
  resourcedetection:
    detectors: [system]
    system:
      hostname_sources: [os]
  # Add this processor to tag metrics with a service name
  resource:
    attributes:
      - key: service.name
        value: "host-monitoring-service"
        action: upsert
  batch:
    send_batch_size: 1000
    timeout: 10s

exporters:
  otlp:
    endpoint: "localhost:4317"
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [resourcedetection, resource, batch]
      exporters: [otlp]
