using System.Diagnostics;
using System.Text;

namespace ProcessWatchdog;

internal static class ReportWriter
{
    internal static string Write(SessionLogger session, Process excelProcess, string outputDir, uint thresholdMs)
    {
        var verdict = DetermineVerdict(session);
        var sb = new StringBuilder();

        sb.AppendLine("# Excel Process Watchdog — Sign-off Report");
        sb.AppendLine();
        sb.AppendLine($"| Field | Value |");
        sb.AppendLine($"|-------|-------|");
        sb.AppendLine($"| Date | {session.SessionStart:yyyy-MM-dd} |");
        sb.AppendLine($"| Session Start | {session.SessionStart:HH:mm:ss} |");
        sb.AppendLine($"| Session End | {session.SessionEnd:HH:mm:ss} |");
        sb.AppendLine($"| Duration | {FormatDuration(session.SessionDuration)} |");
        sb.AppendLine($"| Excel PID | {excelProcess.Id} |");
        sb.AppendLine($"| Freeze Threshold | {thresholdMs}ms |");
        sb.AppendLine($"| **Verdict** | **{VerdictEmoji(verdict)} {verdict}** |");
        sb.AppendLine();

        if (session.FreezeCount == 0)
        {
            sb.AppendLine("## Result");
            sb.AppendLine();
            sb.AppendLine("No freeze events detected during the session.");
        }
        else
        {
            sb.AppendLine("## Freeze Events");
            sb.AppendLine();
            sb.AppendLine($"| # | Start Time | Duration | CPU at Freeze | Severity |");
            sb.AppendLine($"|---|-----------|----------|---------------|----------|");
            int i = 1;
            foreach (var ev in session.Events)
            {
                sb.AppendLine($"| {i++} | {ev.StartTime:HH:mm:ss.fff} | {ev.Duration.TotalSeconds:F3}s | {ev.PeakCpuPercent:F1}% | {ev.Severity} |");
            }
            sb.AppendLine();

            sb.AppendLine("## Summary");
            sb.AppendLine();
            sb.AppendLine($"- **Freeze count:** {session.FreezeCount}");
            sb.AppendLine($"- **Total freeze time:** {session.TotalFreezeTime.TotalSeconds:F3}s");
            sb.AppendLine($"- **Longest freeze:** {session.LongestFreeze.TotalSeconds:F3}s");
            sb.AppendLine($"- **Average freeze:** {session.AverageFreeze.TotalSeconds:F3}s");
            sb.AppendLine();

            var highCpuCount = session.Events.Count(e => e.PeakCpuPercent >= 80);
            if (highCpuCount > 0)
                sb.AppendLine($"- **CPU correlation:** {highCpuCount}/{session.FreezeCount} freezes had CPU ≥ 80% (Excel busy calculating — expected during formula injection)");
            else
                sb.AppendLine($"- **CPU correlation:** Low CPU during freezes — investigate possible deadlock or I/O wait");
        }

        sb.AppendLine();
        sb.AppendLine("## Sign-off Criteria");
        sb.AppendLine();
        sb.AppendLine("| Criterion | Threshold | Result |");
        sb.AppendLine("|-----------|-----------|--------|");
        sb.AppendLine($"| No freeze events | 0 | {Check(session.FreezeCount == 0)} {session.FreezeCount} event(s) |");
        sb.AppendLine($"| Longest freeze < 3s | < 3s | {Check(session.LongestFreeze.TotalSeconds < 3)} {session.LongestFreeze.TotalSeconds:F3}s |");
        sb.AppendLine($"| Total freeze time < 10s | < 10s | {Check(session.TotalFreezeTime.TotalSeconds < 10)} {session.TotalFreezeTime.TotalSeconds:F3}s |");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine($"*Generated by ProcessWatchdog on {session.SessionStart:yyyy-MM-dd HH:mm:ss}*");

        Directory.CreateDirectory(outputDir);
        var fileName = $"watchdog-report-{session.SessionStart:yyyyMMdd-HHmmss}.md";
        var filePath = Path.Combine(outputDir, fileName);
        File.WriteAllText(filePath, sb.ToString());
        return filePath;
    }

    private static string DetermineVerdict(SessionLogger session)
    {
        if (session.FreezeCount == 0) return "PASS";
        if (session.LongestFreeze.TotalSeconds >= 3.0) return "FAIL";
        return "CAUTION";
    }

    private static string VerdictEmoji(string verdict) => verdict switch
    {
        "PASS" => "✅",
        "CAUTION" => "⚠️",
        "FAIL" => "❌",
        _ => ""
    };

    private static string Check(bool pass) => pass ? "✅" : "❌";

    private static string FormatDuration(TimeSpan ts)
    {
        if (ts.TotalHours >= 1) return $"{(int)ts.TotalHours}h {ts.Minutes}m {ts.Seconds}s";
        if (ts.TotalMinutes >= 1) return $"{ts.Minutes}m {ts.Seconds}s";
        return $"{ts.Seconds}s";
    }
}
