{
 "title": "Host Metrics",
 "tags": [ "host-metrics" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "CPU Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_load_average_1m_ratio",
     "legendFormat": "Load Avg 1m"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "system_memory_usage_bytes", "legendFormat": "Memory {{state}}" }
   ]
  },
  {
   "title": "Filesystem Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "system_filesystem_usage_bytes", "legendFormat": "{{device}} - {{mountpoint}}" }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(system_network_io_bytes_total[1m])",
     "legendFormat": "{{device}} - {{direction}}"
    }
   ]
  }
 ]
}